spring.application.name=openai

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.openai.api-key=${OPENAI_API_KEY}

#spring.ai.openai.chat.options.model=ai/gemma3
#spring.ai.openai.api-key=dummy_key
#spring.ai.openai.chat.base-url=http://localhost:12434/engines

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:D:\\Projects\\openai\\src\\main\\resources\\chatmemory;AUTO_SERVER=true
spring.datasource.username=abhishek
spring.datasource.password=12345

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.docker.compose.stop.command=stop

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=openai_collection